<a href="https://colab.research.google.com/github/MRdvan/Pytorch-Training/blob/master/Pytorch-fundamentals-to-deploy/Pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor_a = torch.rand(7,7)
tensor_a

tensor([[0.8873, 0.3943, 0.9899, 0.3388, 0.8589, 0.1600, 0.9863],
        [0.0168, 0.9274, 0.5678, 0.7246, 0.2254, 0.1854, 0.3327],
        [0.1869, 0.8089, 0.1804, 0.9661, 0.6378, 0.3153, 0.5133],
        [0.4044, 0.6061, 0.4186, 0.9303, 0.0710, 0.5751, 0.3562],
        [0.6157, 0.0474, 0.0823, 0.8649, 0.0344, 0.6192, 0.9027],
        [0.2834, 0.1689, 0.2880, 0.9665, 0.8732, 0.9413, 0.7846],
        [0.9681, 0.0868, 0.7168, 0.5830, 0.5072, 0.2427, 0.4829]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_b = torch.rand(1,7)

# Perform matrix multiplication  
tensor_mm = tensor_a.matmul(tensor_b.T)
tensor_mm

tensor([[2.0881],
        [1.3229],
        [1.6670],
        [1.6171],
        [1.8346],
        [2.4254],
        [1.6229]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
import random
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7,7)
tensor_b = torch.rand(1,7)

# Matrix multiply tensors
tensor_mm = tensor_a.matmul(tensor_b.T)
tensor_mm,tensor_mm.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch
device = "cuda" if torch.cuda.is_available() else "cpu" 


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
tensor_a = torch.rand(2,3).to(device)
tensor_b = torch.rand(2,3).to(device)
tensor_a,tensor_b

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_mm = tensor_a.mm(tensor_b.T)
#tensor_mm = tensor_a @ tensor_b.T

tensor_mm

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value=tensor_mm.max()

# Find min
min_value=tensor_mm.min()
max_value,min_value

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_value=tensor_mm.argmax()

# Find arg min
min_value=tensor_mm.argmin()
max_value,min_value

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_c = torch.rand(1,1,1,10)
print(f"{tensor_c,tensor_c.shape}")
# Remove single dimensions
squeeze_tensor = tensor_c.squeeze()

# Print out tensors and their shapes
squeeze_tensor,squeeze_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]), torch.Size([10]))